python run_inference.py --batch-size 5
python run_inference.py --batch-size 10
python run_inference.py --batch-size 15
python run_inference.py --batch-size 20
python run_inference.py --batch-size 25
python run_inference.py --batch-size 30
python run_inference.py --batch-size 35
python run_inference.py --batch-size 40
python run_inference.py --batch-size 45
python run_inference.py --batch-size 50
python run_inference.py --batch-size 55
python run_inference.py --batch-size 60